/**
 * Brand images are served from `public/` rather than imported, so they stay out
 * of the JavaScript bundle and are fetched in parallel with it. `WORDMARK` is
 * generated by `node scripts/optimize-images.mjs`; `LOGO_SQUARE` is the icon
 * referenced by the Organization schema, the manifest and share cards, so its
 * path and dimensions must match `src/lib/seo.ts`.
 */
export const WORDMARK = {
  src: "/calendra-wordmark.webp",
  width: 628,
  height: 205,
} as const;

export const LOGO_SQUARE = {
  src: "/calendra-logo.png",
  width: 512,
  height: 512,
} as const;
