FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm config set registry https://registry.npmjs.org/ \
 && npm ci --no-audit --no-fund

COPY . .

ARG VITE_SITE_URL=https://calendra.si
ARG VITE_APP_BASE_URL=https://app.calendra.si
ARG VITE_CUSTOMER_MARKETPLACE_PUBLIC=false
ARG VITE_LINKEDIN_URL=
ARG VITE_YOUTUBE_URL=
ARG VITE_GOOGLE_PLAY_URL=
ARG VITE_APP_STORE_URL=
ARG VITE_UMAMI_WEBSITE_ID=
ARG VITE_UMAMI_SCRIPT_URL=/stats/script.js
ARG VITE_UMAMI_HOST_URL=/stats
ARG VITE_GOOGLE_ANALYTICS_ID=G-DVDT4W7BYS
ARG VITE_GOOGLE_SITE_VERIFICATION=
ARG VITE_BING_SITE_VERIFICATION=
ARG VITE_ENTITY_PROFILE_URLS=
ARG VITE_AUTHOR_PROFILE_URLS=
ARG VITE_COMPANY_VAT_ID=
ARG VITE_COMPANY_REGISTRATION_NUMBER=
ARG VITE_WIKIDATA_ENTITY_ID=
ARG INDEXNOW_KEY=
ENV VITE_SITE_URL=$VITE_SITE_URL
ENV VITE_APP_BASE_URL=$VITE_APP_BASE_URL
ENV VITE_CUSTOMER_MARKETPLACE_PUBLIC=$VITE_CUSTOMER_MARKETPLACE_PUBLIC
ENV VITE_LINKEDIN_URL=$VITE_LINKEDIN_URL
ENV VITE_YOUTUBE_URL=$VITE_YOUTUBE_URL
ENV VITE_GOOGLE_PLAY_URL=$VITE_GOOGLE_PLAY_URL
ENV VITE_APP_STORE_URL=$VITE_APP_STORE_URL
ENV VITE_UMAMI_WEBSITE_ID=$VITE_UMAMI_WEBSITE_ID
ENV VITE_UMAMI_SCRIPT_URL=$VITE_UMAMI_SCRIPT_URL
ENV VITE_UMAMI_HOST_URL=$VITE_UMAMI_HOST_URL
ENV VITE_GOOGLE_ANALYTICS_ID=$VITE_GOOGLE_ANALYTICS_ID
ENV VITE_GOOGLE_SITE_VERIFICATION=$VITE_GOOGLE_SITE_VERIFICATION
ENV VITE_BING_SITE_VERIFICATION=$VITE_BING_SITE_VERIFICATION
ENV VITE_ENTITY_PROFILE_URLS=$VITE_ENTITY_PROFILE_URLS
ENV VITE_AUTHOR_PROFILE_URLS=$VITE_AUTHOR_PROFILE_URLS
ENV VITE_COMPANY_VAT_ID=$VITE_COMPANY_VAT_ID
ENV VITE_COMPANY_REGISTRATION_NUMBER=$VITE_COMPANY_REGISTRATION_NUMBER
ENV VITE_WIKIDATA_ENTITY_ID=$VITE_WIKIDATA_ENTITY_ID
ENV INDEXNOW_KEY=$INDEXNOW_KEY

RUN npm run build

FROM caddy:2-alpine
COPY Caddyfile /etc/caddy/Caddyfile
RUN caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile
COPY --from=build /app/dist /srv

EXPOSE 80
