import { LegalDocument, LegalList, LegalNotice, LegalSection } from "@/components/legal/LegalDocument";
import { LEGAL } from "@/lib/legal";
import { getRoutePath } from "@/lib/localized-routes";
import { useSiteLanguage } from "@/lib/site-language";

const copy = {
  sl: {
    badge: "AI transparentnost",
    title: "AI transparentnost za Calendra",
    intro: "Ta stran pojasnjuje uporabo AI funkcionalnosti v Calendri. Ob začetku produkcije AI funkcije niso omogočene.",
    lastUpdated: "Zadnja posodobitev: 23. junij 2026",
    statusTitle: "1. Status ob produkcijskem zagonu",
    status: LEGAL.aiEnabledAtProductionLaunch
      ? "Izbrane AI funkcionalnosti so lahko omogočene glede na nastavitve najemnika."
      : "AI funkcionalnosti ob začetku produkcije niso omogočene. Ta stran je pripravljena zaradi preglednosti in za primer kasnejše aktivacije AI modulov.",
    providerTitle: "2. Ponudnik AI storitev",
    providerParagraph: "Če bodo AI funkcionalnosti omogočene, lahko Calendra uporablja OpenAI kot ponudnika AI storitev za izbrane funkcionalnosti, kot so glasovni ukazi, pomoč pri obdelavi vsebin ali avtomatizacija delov delovnega toka.",
    dataTitle: "3. Katere podatke lahko obdeluje AI",
    dataItems: [
      "uporabniške vnose, ki jih uporabnik namerno poda v AI funkcijo,",
      "kontekst, potreben za izvedbo izbrane AI funkcije, če je funkcija omogočena,",
      "AI izhode, predloge ali transkripte, ki nastanejo pri uporabi funkcije.",
    ],
    limitsTitle: "4. Omejitve in odgovornost",
    limitsItems: [
      "AI izhodi so lahko napačni, nepopolni ali neprimerni za določen namen,",
      "uporabnik oziroma najemnik mora AI izhod pred uporabo pregledati,",
      "AI ne nadomešča strokovne, pravne, davčne, medicinske, psihološke ali druge regulirane presoje,",
      "najemnik je odgovoren za zakonito uporabo AI funkcij v svojem poslovanju in za obveščanje svojih uporabnikov ali strank, kadar je to potrebno.",
    ],
    controlTitle: "5. Nadzor in nastavitve",
    controlParagraphs: [
      "AI funkcije bodo, kadar bodo omogočene, prikazane v aplikaciji ali nastavitvah. Če funkcija ni omogočena, se podatki ne pošiljajo AI ponudniku za to funkcijo.",
      "Če bo AI funkcionalnost uvedena v prihodnosti, bomo posodobili to stran, politiko zasebnosti in seznam podobdelovalcev, če bo to potrebno.",
    ],
    linksTitle: "Povezani dokumenti",
    links: [
      { label: "Politika zasebnosti", route: "privacy" },
      { label: "Podobdelovalci", route: "subprocessors" },
      { label: "Varnost", route: "security" },
    ] as const,
  },
  en: {
    badge: "AI Transparency",
    title: "AI transparency for Calendra",
    intro: "This page explains Calendra AI features. At production launch, AI features are not enabled.",
    lastUpdated: "Last updated: 23 June 2026",
    statusTitle: "1. Production launch status",
    status: LEGAL.aiEnabledAtProductionLaunch
      ? "Selected AI features may be enabled depending on tenant settings."
      : "AI features are not enabled at production launch. This page is prepared for transparency and for possible later activation of AI modules.",
    providerTitle: "2. AI service provider",
    providerParagraph: "If AI features are enabled, Calendra may use OpenAI as the AI service provider for selected features such as voice commands, content-processing assistance or workflow automation.",
    dataTitle: "3. Data AI may process",
    dataItems: [
      "user inputs intentionally submitted to an AI feature,",
      "context required to perform the selected AI feature where the feature is enabled,",
      "AI outputs, suggestions or transcripts generated by use of the feature.",
    ],
    limitsTitle: "4. Limitations and responsibility",
    limitsItems: [
      "AI outputs may be inaccurate, incomplete or unsuitable for a specific purpose,",
      "the user or tenant must review AI output before using it,",
      "AI does not replace professional, legal, tax, medical, psychological or other regulated judgment,",
      "the tenant is responsible for lawful use of AI features in its business and for notifying its users or customers where required.",
    ],
    controlTitle: "5. Control and settings",
    controlParagraphs: [
      "Where AI features are enabled, they will be shown in the application or settings. If a feature is not enabled, data is not sent to the AI provider for that feature.",
      "If AI functionality is introduced later, we will update this page, the Privacy Policy and the subprocessor list where required.",
    ],
    linksTitle: "Related documents",
    links: [
      { label: "Privacy Policy", route: "privacy" },
      { label: "Subprocessors", route: "subprocessors" },
      { label: "Security", route: "security" },
    ] as const,
  },
};

const AITransparency = () => {
  const { language } = useSiteLanguage();
  const c = copy[language];

  return (
    <LegalDocument badge={c.badge} title={c.title} intro={c.intro} lastUpdated={c.lastUpdated}>
      <LegalSection title={c.statusTitle} tone="highlight">
        <LegalNotice>{c.status}</LegalNotice>
      </LegalSection>
      <LegalSection title={c.providerTitle}>
        <p>{c.providerParagraph}</p>
      </LegalSection>
      <LegalSection title={c.dataTitle}>
        <LegalList items={c.dataItems} />
      </LegalSection>
      <LegalSection title={c.limitsTitle}>
        <LegalList items={c.limitsItems} />
      </LegalSection>
      <LegalSection title={c.controlTitle}>
        {c.controlParagraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}
      </LegalSection>
      <LegalSection title={c.linksTitle}>
        <div className="flex flex-wrap gap-3">
          {c.links.map((link) => (
            <a key={link.route} href={getRoutePath(link.route, language)} className="rounded-full border border-border/60 px-4 py-2 text-sm font-medium text-foreground transition-colors hover:border-primary/40 hover:bg-primary/[0.05]">
              {link.label}
            </a>
          ))}
        </div>
      </LegalSection>
    </LegalDocument>
  );
};

export default AITransparency;
