/**
 * Downloads the latin and latin-ext WOFF2 subsets used by the site into
 * public/fonts and writes src/styles/fonts.css to match.
 *
 * Fonts are self-hosted rather than linked from Google Fonts because the
 * stylesheet link is render-blocking on a third-party origin: the browser must
 * resolve DNS, negotiate TLS and fetch a stylesheet before it can even discover
 * the font files. Serving them from our own origin removes that round trip
 * entirely, and Slovenian text needs latin-ext for č, š and ž.
 *
 * This is a maintenance script, not part of the build. Run it only when a
 * family or weight range changes, then commit the results:
 *
 *   node scripts/fetch-fonts.mjs
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createFontStack } from '@capsizecss/core';
import arial from '@capsizecss/metrics/arial';
import dmSansMetrics from '@capsizecss/metrics/dMSans';
import helvetica from '@capsizecss/metrics/helvetica';
import plusJakartaSansMetrics from '@capsizecss/metrics/plusJakartaSans';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');
const fontsDir = path.join(projectRoot, 'public', 'fonts');
const cssPath = path.join(projectRoot, 'src', 'styles', 'fonts.css');
const stackPath = path.join(projectRoot, 'src', 'styles', 'font-stacks.json');

// Google serves woff2 only to user agents it recognises as supporting it.
const MODERN_UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const WANTED_SUBSETS = ['latin', 'latin-ext'];

const families = [
  {
    // Body text. The opsz axis is pinned so one file covers every size.
    cssFamily: 'DM Sans',
    fileBase: 'dm-sans',
    url: 'https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,300..700&display=swap',
    metrics: dmSansMetrics,
    key: 'sans',
  },
  {
    // Headings only, so the range starts at medium.
    cssFamily: 'Plus Jakarta Sans',
    fileBase: 'plus-jakarta-sans',
    url: 'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@500..800&display=swap',
    metrics: plusJakartaSansMetrics,
    key: 'display',
  },
];

/**
 * Google's css2 response is a sequence of @font-face blocks, each preceded by a
 * `/* subset *\/` comment. The comment is the only reliable way to tell which
 * unicode-range belongs to which subset.
 */
const parseFaces = (css) => {
  const faces = [];
  const pattern = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;

  for (const [, subset, body] of css.matchAll(pattern)) {
    const src = /src:\s*url\(([^)]+)\)/.exec(body)?.[1];
    const unicodeRange = /unicode-range:\s*([^;]+);/.exec(body)?.[1]?.trim();
    const weight = /font-weight:\s*([^;]+);/.exec(body)?.[1]?.trim();
    const style = /font-style:\s*([^;]+);/.exec(body)?.[1]?.trim() ?? 'normal';

    if (src && unicodeRange && weight) faces.push({ subset, src, unicodeRange, weight, style });
  }

  return faces;
};

await fs.mkdir(fontsDir, { recursive: true });
await fs.mkdir(path.dirname(cssPath), { recursive: true });

const blocks = [
  '/**',
  ' * Self-hosted font subsets. Generated by `node scripts/fetch-fonts.mjs`;',
  ' * edit that script rather than this file.',
  ' *',
  ' * `font-display: swap` renders text immediately in the fallback and swaps',
  ' * once the face arrives, which keeps text visible during load rather than',
  ' * trading a blank paragraph for a slightly tidier swap.',
  ' *',
  ' * Each family is paired with a `... Fallback` face: a local system font with',
  ' * its ascent, descent and advance widths overridden to match the web font.',
  ' * Without it the swap reflows every block of text on the page, which showed',
  ' * up as the entire Cumulative Layout Shift budget being spent on fonts.',
  ' */',
  '',
];

const fontStacks = {};

for (const family of families) {
  const response = await fetch(family.url, { headers: { 'User-Agent': MODERN_UA } });
  if (!response.ok) throw new Error(`Failed to fetch CSS for ${family.cssFamily}: HTTP ${response.status}`);

  const faces = parseFaces(await response.text()).filter((face) => WANTED_SUBSETS.includes(face.subset));
  if (faces.length === 0) throw new Error(`No latin/latin-ext faces found for ${family.cssFamily}.`);

  for (const face of faces) {
    const fileName = `${family.fileBase}-${face.subset}.woff2`;
    const fontResponse = await fetch(face.src, { headers: { 'User-Agent': MODERN_UA } });
    if (!fontResponse.ok) throw new Error(`Failed to download ${face.src}: HTTP ${fontResponse.status}`);

    const bytes = Buffer.from(await fontResponse.arrayBuffer());
    await fs.writeFile(path.join(fontsDir, fileName), bytes);
    console.log(`Saved public/fonts/${fileName} (${(bytes.length / 1024).toFixed(1)} KB)`);

    blocks.push(
      '@font-face {',
      `  font-family: "${family.cssFamily}";`,
      `  font-style: ${face.style};`,
      `  font-weight: ${face.weight};`,
      '  font-display: swap;',
      `  src: url("/fonts/${fileName}") format("woff2");`,
      `  unicode-range: ${face.unicodeRange};`,
      '}',
      '',
    );
  }

  const { fontFaces, fontFamily } = createFontStack([family.metrics, helvetica, arial]);
  blocks.push(fontFaces.trim(), '');
  fontStacks[family.key] = fontFamily;
}

await fs.writeFile(cssPath, blocks.join('\n'), 'utf8');
console.log(`Wrote ${path.relative(projectRoot, cssPath)}`);

await fs.writeFile(stackPath, `${JSON.stringify(fontStacks, null, 2)}\n`, 'utf8');
console.log(`Wrote ${path.relative(projectRoot, stackPath)}`);
